### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by nathanmusoke** [ipython/ipython-website#107]
http://ipython.org/citing.html has a link to http://fperez.org/papers/ipython07_pe-gr_cise.pdf, however, it is broken.

**Comment by takluyver** [comment]
@fperez I think we need you to fix this one. It looks like the entire papers/ directory of your personal site is empty: http://fperez.org/papers/

**Comment by nathanmusoke** [comment]
There is a pdf at https://bugs.python.org/file28188/ if you want a temporary fix.

**Comment by fperez** [comment]
Huh, that's weird... No idea why that directory got wiped, just fixed it. Thanks for the report!
