### ISSUE TITLE
Remove paypal button,

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython-website#108]
Was asked on the steering ML. 

Same for Jupyter.

**Comment by takluyver** [comment]
We need to replace it with a [Flipcause](https://www.flipcause.com/) button, not just remove it entirely.

I think we need probably need a code of some kind from NumFOCUS to direct the money to their account. Who do we need to contact to work that out?

**Comment by jasongrout** [comment]
When was that email? I don't remember seeing something like this.

**Comment by takluyver** [comment]
It was to named individuals rather than any mailing list. And, my mistake, they did send us the integration code we need to put on the website. Not sure if I should post it publicly, though presumably it ends up public once the website is changed anyway. I'll have a crack at a PR.
