### ISSUE TITLE
FlipCause button is not secure

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython-website#110]
As Pointed by @takluyver on https://github.com/ipython/ipython-website/pull/109 the flipcause button is **not** secure as it is on an http page. 
(Yes it is iframe, but regardless) 

We should **not** allow it on http page, or, open a new page.

**Comment by takluyver** [comment]
It should be easy to make it open a new page, because it already does that on mobile - we'd just disable the user-agent sniffing [here](https://github.com/ipython/ipython-website/blob/111c433e64b82383f7d35262ce3f6a6426c9de0f/themes/agogo/layout.html#L24).
