### ISSUE TITLE
updated NumFOCUS donor link

### ISSUE THREAD

**Issue by lisamartin72** [ipython/ipython-website#146]
Hi, I am a new staff member at NumFOCUS. We have updated our donation provider from Flipcause to Salsa. The new link is: 

https://numfocus.salsalabs.org/donate-to-ipython/index.html

Please update your website accordingly. : )

Thanks, 

Lisa Martin
NumFOCUS

**Comment by Carreau** [comment]
Hi Lisa, 

Thanks and welcome to Numfocus, we are looking forward to work with you. 

If you are interacting on behalf of Numfocus, may I suggest you ask to be added to the numfocus organization (https://github.com/numfocus), and if you are already part of it, to make your  belonging to the organization public (head to https://github.com/orgs/numfocus/people?utf8=%E2%9C%93&query=lisamartin72 and set to public); that will make it easier to verify someone is just not trying to make us change donation links to divert funds :-) 

I should have updated the IPython website to point to the new URL. Closing as this should be fixed, but feel free to keep commenting.

Thanks,

**Comment by lisamartin72** [comment]
Thanks Matthias!

I’ll get that done today. I have updated my Github profile in the last hour to include my NumFOCUS email as well. 

Best,

Lisa
