### ISSUE TITLE
books added

### ISSUE THREAD

**Issue by ankit404** [ipython/ipython-website#148]
[Introduction to Algorithms, Thi - Thomas H. Cormen, Charles E. Le.pdf](https://github.com/ipython/ipython-website/files/3675716/Introduction.to.Algorithms.Thi.-.Thomas.H.Cormen.Charles.E.Le.pdf)
[Uploading Introduction to Algorithms, Thi - Thomas H. Cormen, Charles E. Le.pdf…]()

**Comment by ankit404** [comment]
added a book

**Comment by takluyver** [comment]
The books section of the website lists books about IPython & Jupyter. At a glance, the Introduction to Algorithms is not especially relevant.
