### ISSUE TITLE
Citing IPython

### ISSUE THREAD

**Issue by Chandramohan01** [ipython/ipython-website#158]

**Comment by Chandramohan01** [comment]
There is grammatical mistake in Citing IPython section.

**Comment by slel** [comment]
Hacktoberfest spam? If this is for Hacktoberfest, please read their
detailed rules carefully. They encourage meaningful contributions
and discourage pull requests with no clear added value and whose
only purpose seems to be to increase your "score".

In this case the grammar is in fact correct. On the other hand,
"There is grammatical mistake" is incorrect and should instead
read "There is a grammatical mistake".

https://hacktoberfest.digitalocean.com/details
